import React, { FC } from "react";
import ServiceOverViewMapWrap from "./style/wrap";
import Grid from "@mui/material/Unstable_Grid2";
import { Stack } from "@mui/system";
import { P2 } from "@components/shared/paragraph";
import { Check, Computer } from "@mui/icons-material";

const ServiceOverViewMap: FC = () => {
    return (
        <ServiceOverViewMapWrap>
            <Grid
                spacing={4}
                container>
                {
                    skills.map((i, index) => (
                        <Grid
                            key={index}
                            lg={3}
                            md={4}
                            sm={6}
                            xs={12}>
                            <Stack
                                spacing={2}
                                direction="row">
                                <Computer/>
                                <P2>{i}</P2>
                            </Stack>
                        </Grid>
                    ))
                }
            </Grid>
        </ServiceOverViewMapWrap>
    );
};

const skills = [
    ".NET",
    ".NET 5.0/6",
    ".NET Core",
    ".NET Core Web API",
    "4D",
    "A-GPS",
    "A/B Testing",
    "A+ Certified IT Technician",
    "A+ Certified Professional",
    "Ab Initio",
    "ABAP List Viewer (ALV)",
    "ABAP Web Dynpro",
    "Abaqus",
    "ABIS",
    "AbleCommerce",
    "Ableton",
    "Ableton Live",
    "Ableton Push",
    "AC3",
    "ACARS",
    "Active Directory",
    "ActiveCampaign",
    "Ada programming",
    "ADF / Oracle ADF",
    "ADO.NET",
    "Adobe Acrobat",
    "Adobe Air",
    "Adobe Analytics",
    "Adobe Animate",
    "Adobe Audition",
    "Adobe Captivate",
    "Adobe Creative Cloud",
    "Adobe Dynamic Tag Management",
    "Adobe Experience Manager",
    "Adobe Freehand",
    "Adobe Illustrator",
    "Adobe Muse",
    "Adobe Pagemaker",
    "Adobe Premiere Pro",
    "Adobe Systems",
    "Adobe Workfront",
    "Adobe XD",
    "Advanced Business Application",
    "Affectiva",
    "Agile Development",
    "Alibre Design",
    "Alienbrain",
    "All-Source Analysis",
    "AlphaCAM",
    "Alpine JS",
    "Altera Quartus",
    "Alteryx",
    "Altium Designer",
    "Altium NEXUS",
    "Alvarion",
    "Amazon App Development",
    "Amazon CloudFormation",
    "Amazon CloudFront",
    "Amazon ECS",
    "Amazon FBA",
    "Amazon Listings Optimization",
    "Amazon Product Launch",
    "Amazon S3",
    "Amazon Web Services",
    "Amibroker Formula Language",
    "AMQP",
    "Analytics",
    "Anaplan",
    "Android App Development",
    "Android SDK",
    "Android Studio",
    "Android Wear SDK",
    "Angular",
    "Angular 4",
    "Angular 6",
    "Angular Material",
    "AngularJS",
    "Ansible",
    "Ansys",
    "Apache",
    "Apache Ant",
    "Apache Hadoop",
    "Apache Kafka",
    "Apache Maven",
    "Apache Solr",
    "Apache Spark",
    "API",
    "API Development",
    "API Integration",
    "API Testing",
    "Apigee",
    "Apollo",
    "App Developer",
    "App Development",
    "App Localization",
    "App Publication",
    "App Reskin",
    "Appfolio",
    "Appian BPM",
    "Apple Safari",
    "Apple UIKit",
    "Apple Xcode",
    "Applescript",
    "Application Packaging",
    "Application Performance",
    "Apttus",
    "AR / VR 3D Asset",
    "ArangoDB",
    "Arc",
    "ArcGIS",
    "ArchiCAD",
    "Architectural Engineering",
    "ArcMap",
    "ARCore",
    "Arena Simulation Programming",
    "Argus Monitoring Software",
    "Ariba",
    "ARKit",
    "Binary Search",
    "Bioinformatics",
    "Biostatistics",
    "BIRT Development",
    "Bitcoin",
    "BitMEX",
    "BitMEX API",
    "Bitrix",
    "Biztalk",
    "Blazor",
    "Blender",
    "Blockchain",
    "Blog Install",
    "Bluebeam",
    "Bluetooth Low Energy (BLE)",
    "BMC Remedy",
    "Boonex Dolphin",
    "Boost",
    "Bower",
    "Computer Security",
    "Computer Vision",
    "Construct 3",
    "CMS",
    "Copyright",
    "Corda",
    "Cordana",
    "Core PHP",
    "Corel Draw",
    "Corteza",
    "cPanel",
    "CRE Loaded",
    "Creo",
    "Crestron",
    "Cross Browser",
    "Cryptocurrency",
    "CS-Cart",
    "CSS2",
    "CSS3",
    "CubeCart",
    "CUDA",
    "cURL",
    "Digital Operations",
    "Digital Signal Processing",
    "Digital System Engineering",
    "DigitalOcean",
    "DirectX",
    "Discord API",
    "Distributed Systems",
    "Django",
    "DNS",
    "Docker",
    "Docker Compose",
    "ERP Software",
]

export default ServiceOverViewMap;
